TicketTool.Projects/TicketTool.Projects.Zzt/TicketTool.Projects.Zzt.Web.MVC/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Web.Compilation;
using System.Web.Mvc;
using Zzt.Web.MVC.BusinessLogic;
using Zzt.Web.MVC.CatalogueService;
using Zzt.Web.MVC.Extensions;
using Zzt.Web.MVC.Models;
using Zzt.Web.MVC.ProductsCatalogue;
using CustomerOrder = Zzt.Web.MVC.Models.CustomerOrder;
using OrderLine = Zzt.Web.MVC.Models.OrderLine;

namespace Zzt.Web.MVC.Controllers
{
#if !DEBUG
    [Authorize]
#endif
    public class OrdersController : BaseController
    {
        private OrderProcessing _orderProcessing;
        private List<long> _defaultArticles;
        private List<long> _excludeArticles;

        private OrderProcessing OrderProcessing
        {
            get { return _orderProcessing ?? (_orderProcessing = new OrderProcessing()); }
        }

        private List<long> DefaultArticles
        {
            get { return this._defaultArticles ?? (this._defaultArticles = GetArticles("DefaultArticles")); }
        }

        private List<long> ExcludeArticles
        {
            get { return this._excludeArticles ?? (this._excludeArticles = GetArticles("ExcludeArticles")); }
        }

        protected override void Dispose(bool disposing)
        {
            if (OrderProcessing != null)
                OrderProcessing.Dispose();
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult Copy(string id)
        {
            CustomerOrder order = null;

            if (!string.IsNullOrEmpty(id))
            {
                string message, sapCode;
                order = OrderProcessing.GetOrder(id, out message, out sapCode);
                SapCode = sapCode ?? SapCode;
                if (order == null)
                    ErrorMessage(message);
                else
                    ValidateOrderLines(order.OrderLines);
            }
            var model = new EditOrder(order == null ? null : "Редактирование копии заказа")
            {
                Order = order ?? new CustomerOrder(),
            };
            model.Order.OrderId = null;
            model.Order.OrderStatusHistory = new List<OrderStatusChange>();
            model.Order.SystemComment = string.Empty;
            model.Order.OriginalOrderId = id;
            model.Order.CustomerComment = string.Empty;
            model.Order.CitySelectListItems(OrderProcessing.CatalogueService);
            model.Order.DeliveryTypeSelectListItems(OrderProcessing.CatalogueService);            
            return Index(this.InitDadataSettings(model));
        }

        [HttpGet]
        public ActionResult Index(string id)
        {
            CustomerOrder order = null;

            if (!string.IsNullOrEmpty(id))
            {
                string message, sapCode;
                order = OrderProcessing.GetOrder(id, out message, out sapCode);
                SapCode = sapCode ?? SapCode;
                if (order == null)
                    ErrorMessage(message);
                else
                    ValidateOrderLines(order.OrderLines);
            }
            var model = new EditOrder(order == null ? null : "Редактирование заказа")
            {
                Order = order ?? new CustomerOrder(),
            };
            model.Order.CitySelectListItems(OrderProcessing.CatalogueService);
            model.Order.DeliveryTypeSelectListItems(OrderProcessing.CatalogueService);

            return View(this.InitDadataSettings(model));
        }

        [HttpPost]
        public ActionResult Index(EditOrder model, bool? save = null)
        {
            save = save ?? false;

            if (model != null && model.Order != null)
            {
                ValidateOrderLines(model.Order.OrderLines);

                if (save.Value && ModelState.IsValid)
                {
                    string message;
                    if (string.IsNullOrEmpty(model.Order.OrderId)
                            ? OrderProcessing.Create(model.Order, SapCode, out message)
                            : OrderProcessing.Update(model.Order, SapCode, out message))
                        return RedirectToAction("Index",new {id=model.Order.OrderId});//return Index(model.Order.OrderId);
                    ErrorMessage(message);
                }
            }
            else
                ModelState.AddModelError("Order", "Заказ не найден");

            if(!save.Value)
                ModelState.Clear();

            if (ModelState.Any(s => s.Value.Errors.Any()))
            {
                ModelState
                    .Where(s => s.Key.LastIndexOf('.') > -1)
                    .Select(s => new {Error = s.Value.Errors.FirstOrDefault(), Property = typeof (CustomerOrder).GetProperty(s.Key.Substring(s.Key.LastIndexOf('.') + 1))})
                    .Where(x => x.Error != null)
                    .Select(x => new
                    {
                        Error = x.Error.ErrorMessage,
                        Attribute = x.Property == null ? null : x.Property.GetCustomAttributes(true)
                            .Where(a => a as DisplayAttribute != null)
                            .Cast<DisplayAttribute>()
                            .FirstOrDefault()
                    })
                    .Select(x => new {x.Error, Name = x.Attribute != null ? x.Attribute.Name : String.Empty})
                    .Select(x => String.IsNullOrEmpty(x.Name) ? x.Error : String.Concat(x.Name, ": ", x.Error))
                    .ToList()
                    .ForEach(ErrorMessage);
                //ErrorMessage("Заказ не был сохранён. Проверьте заполнение обязательных полей.");
            }

            if (model != null && model.Order != null && !string.IsNullOrEmpty(model.Order.OrderId))
                model.Header = "Редактирование заказа";
            
            if (model != null 
                && model.Order != null 
                && string.IsNullOrEmpty(model.Order.OrderId) 
                && !string.IsNullOrEmpty(model.Order.OriginalOrderId))
                model.Header = "Редактирование копии заказа";

            return View("Index", this.InitDadataSettings(model));
        }

        private void ValidateOrderLines(List<OrderLine> lines)
        {
            if (lines == null || !lines.Any())
            {
                ModelState.AddModelError("Order.OrderLines", "Добавьте хотя бы 1 позицию");
                return;
            }

            try
            {
                var getItemsResponse = OrderProcessing.OrdersBackendServiceClient.GetArticleStockStatus(
                    new GetItemsRequest
                        {
                            Articles = lines.Select(l => l.ArticleNo.ToString(CultureInfo.InvariantCulture)).Where(s => !string.IsNullOrWhiteSpace(s)).ToArray(),
                            SaleLocation = SapCode,
                            Channel = ((string)AppSettingsExpressionBuilder.GetAppSetting("ProductServiceChannel")),
                        });

                if (getItemsResponse.Items == null || !getItemsResponse.Items.Any())
                    return;

                if (getItemsResponse.Items != null && getItemsResponse.Items != null && getItemsResponse.Items.GroupBy(d => d.Article).Count() != lines.GroupBy(l => l.ArticleNo).Count())
                {
                    var notFound = lines.GroupBy(l => l.ArticleNo).Where(l => getItemsResponse.Items.All(d => d.Article != l.Key)).Select(l => l.Key);
                    foreach (var l in notFound)
                        ModelState.AddModelError("Order.OrderLines", string.Format("Артикул {0} не найден", l));
                }

                for (var j = 0; j < lines.Count; j++)
                {
                    var orderLine = lines[j];
                    var article = getItemsResponse.Items.FirstOrDefault(i => i.Article == orderLine.ArticleNo);
                    var orderLineErrorKey = string.Format("Order.OrderLines[{0}].ArticleNo", j);
                    if (article == null)
                    {
                        ModelState.AddModelError(orderLineErrorKey, string.Format("Артикул не найден"));
                        continue;
                    }

                    if (!this.ExcludeArticles.Contains(article.Article))
                        orderLine.ArticleTitle = article.Title;
                    else
                    {
                        if (String.IsNullOrEmpty(orderLine.ArticleTitle))
                            orderLine.ArticleTitle = article.Title;
                    }

                    orderLine.LongTail = article.IsLongTail;
                    if (!this.ExcludeArticles.Contains(article.Article) && 
                        (article.Qty == 0 || orderLine.Quantity > article.Qty) &&
                        !String.Equals(orderLine.UmaxStatus, "проведен", StringComparison.InvariantCultureIgnoreCase))
                    {
                        ModelState.AddModelError(orderLineErrorKey, string.Format("На складе {0} шт.", article.Qty));
                    }
                    if (this.DefaultArticles.Contains(article.Article))
                    {
                        orderLine.Price = article.Price.HasValue ? article.Price.Value : default(decimal);
                    }
                }
            }
            catch (Exception e)
            {
                Message(MessageType.Error, e.Message);
                Logger.Error(e.Message, e);
            }
        }

        [HttpGet]
        public ActionResult CreateOrder()
        {
            var basketArticles=new List<BasketArticle>();
            var orderId = string.Empty;
            object tempBasketObject = Session["createOrderRequest"];
            if (tempBasketObject != null)
            {
                var tempBasket = (Tuple<string, List<BasketArticle>>) tempBasketObject;

TicketTool.Projects/TicketTool.Projects.Zzt/TicketTool.Projects.Zzt.Web.MVC/Views/Shared/EditorTemplates/DateTimeView.cshtml
@model DateTime?
@{
    var offset = Convert.ToInt32(System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting("MedvedevTime"));
}

<div class="controls" style="padding-bottom: 5px;">
    <input type="text" name="@(Html.NameForModel())_date" id="@(Html.IdForModel())_date" value="@((Model ?? DateTime.Now).Date.ToString("dd.MM.yyyy"))"/>       
    <span style="position: absolute;font-size: 0.7em;color:#8B8B8B;padding-top: 5px;padding-left: 9px;">
        <i class="ui-icon ui-blue ui-icon-info" style="position: absolute;margin-top: 2px;"></i>
        <span style="margin-left: 20px;">&uarr;&nbsp;&nbsp;&darr;  &plusmn; 1 час</span>
    </span>
    <input type="hidden" name="@(Html.NameForModel())" id="@Html.IdForModel()" value="@(Model ?? DateTime.Now)"/>
    <br/>
    @Html.ValidationMessageFor(m => m)
</div>

TicketTool.Projects/TicketTool.Projects.Zzt/TicketTool.Projects.Zzt.Web.MVC/Views/Shared/EditorTemplates/OrderLineView.cshtml
@model Zzt.Web.MVC.Models.OrderLine

@{
    var index = (ViewData["index"] as int?) ?? 0;
    index++;
}

<tr>
    <td>
        @(index)
    </td>
    <td>
        <a href="#" onclick="addNewLine('@Model.ArticleNo')">@Html.DisplayFor(m => m.ArticleNo, new {@class = "control-label"})</a>
        @Html.ValidationMessageFor(m => m.ArticleNo)
        <br/>
        @Html.HiddenFor(m => m.ArticleNo)
        <br/>
        <br/>
        @if (!string.IsNullOrEmpty(Model.UmaxStatus))
        {
            @Html.LabelFor(m => m.UmaxStatus)
            @Html.Label("m => m.UmaxStatus", Model.UmaxStatus.ToLowerInvariant())
            @Html.HiddenFor(m => m.UmaxStatus)
        }
        <br/>
        @if (Model.LongTail)
        {
            @Html.LabelFor(m => m.LongTail)
        }
        @Html.HiddenFor(m => m.LongTail)
    </td>
    <td>
        <a href="#" onclick=" addNewLine('@Model.ArticleNo') ">@Html.DisplayFor(m => m.ArticleTitle, new { @class = "control-label" })</a>
        @Html.HiddenFor(m => m.ArticleTitle)
    </td>
    <td>
        <i class="img-icon ui-button ui-red ui-icon ui-icon-minusthick" itemref="@Url.Action("LineDec", "Orders", new {position = index - 1})"></i>
        @Html.DisplayFor(m => m.Quantity, new {@class = "control-label"})
        <i class="img-icon ui-button ui-blue ui-icon ui-icon-plusthick" itemref="@Url.Action("LineAdd", "Orders", new {position = index - 1})"></i>
        @Html.ValidationMessageFor(m => m.Quantity)
        <input type="hidden" id="@Html.IdFor(m => m.Quantity)" name="@Html.NameFor(m => m.Quantity)" value="@Model.Quantity"/>
    </td>
    <td>
        @Html.DisplayFor(m => m.PriceText)
        @Html.HiddenFor(m => m.Price)
    </td>
    <td>
        @Html.DisplayFor(m => m.DiscountPercentageText)
        @Html.HiddenFor(m => m.DiscountPercentage)
    </td>
    <td>
        <i class="img-icon ui-button ui-blue ui-icon ui-icon-trash" itemref="@Url.Action("LineDel", "Orders", new {position = index - 1})"></i>
    </td>
</tr>